# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 20:02
from __future__ import unicode_literals

from django.db import migrations

from tiny_migrate.models import OlympicSkier, OlympicCoach


def ski_data(apps, schema_editor):
    OlympicSkier.objects.create(finish=1, name='Marina Kiehl', age=23, country='WGermany', time='85.86')
    OlympicSkier.objects.create(finish=2, name='Brigitte Oertli', age=25, country='Switzerland', time='86.61')
    OlympicSkier.objects.create(finish=3, name='Karen Percy', age=21, country='Canada', time='86.62')
    OlympicSkier.objects.create(finish=4, name='Maria Walliser', age=24, country='Switzerland', time='86.89')
    OlympicSkier.objects.create(finish=5, name='Laurie Graham', age=27, country='Canada', time='86.99')
    OlympicSkier.objects.create(finish=6, name='Petra Kronberger', age=18, country='Austria', time='87.03')
    OlympicSkier.objects.create(finish=7, name='Regine Mosenlechner', age=26, country='WGermany', time='87.16')
    OlympicSkier.objects.create(finish=8, name='Lisi Kirchler', age=24, country='Austria', time='87.19')
    OlympicSkier.objects.create(finish=9, name='Michela Figini', age=21, country='Switzerland', time='87.26')
    OlympicSkier.objects.create(finish=10, name='Lucia Medzihradsk', age=19, country='Czechoslovakia', time='87.28')


def coach_data(apps, schema_editor):
    OlympicCoach.objects.create(name='Skeeter Bob', country='Switzerland', age=42)
    OlympicCoach.objects.create(name='Jane Jetson', country='WGermany', age=38)
    OlympicCoach.objects.create(name='Wilma Flintstone', country='Canada', age=72)
    OlympicCoach.objects.create(name='Maggie Simpson', country='Austria', age=12)
    OlympicCoach.objects.create(name='Bonnie Blair', country='Czechoslovakia', age=32)


class Migration(migrations.Migration):

    dependencies = [
        ('tiny_migrate', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(ski_data),
        migrations.RunPython(coach_data)
    ]
